providers = ['python']

[variables]
PYTHONUNBUFFERED = '1'
PYTHONDONTWRITEBYTECODE = '1'
HOST = '0.0.0.0'
FORCE_CPU = 'true'

[phases.setup]
nixPkgs = ['python39', 'libGL', 'glib', 'libxcrypt-legacy']

[phases.install]
cmds = [
    'pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'echo "Checking model file..."',
    'if [ ! -f "CRDN1000.pkl" ]; then echo "Downloading model..." && python download_model.py; fi',
    'if [ -f "CRDN1000.pkl" ]; then echo "Model file ready"; else echo "Model file missing"; exit 1; fi'
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT app:app --timeout 180 --workers 1 --access-logfile - --error-logfile -"
