# Railway Config as Code for Card Rectification API
# Docs: https://docs.railway.com/reference/config-as-code

[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 5

[deploy.resources]
memory = "2GB"
cpu = "1"

